<?xml version="1.0" encoding="utf-8"?><rss version="2.0" xmlns:blogChannel="http://backend.userland.com/blogChannelModule"><channel><title>臺灣個人資料保護與管理制度</title><link>https://www.vtaiwan.org.tw</link><description>國外動態觀測</description><copyright>Copyright © 經濟部商業司 All Rights Reserved. 經濟部商業司廣告 </copyright><generator /><item><title>【個資保護/資訊安全】歐盟理事會公布擬定的電子隱私規則(The ePrivacy Regulation, ePR)修訂草案</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=63</link><description>歐盟理事會公布擬定的電子隱私規則(The ePrivacy Regulation, ePR)修訂草案，ePR的目標側重於用戶電子通信的機密性，它還將規範以下活動：


	直銷(direct marketing)；
	網站受眾測量(website audience measurement)；
	設備和瀏覽間的通信傳輸；
	用戶機器上設置的cookie。


依據ePR第二段前言(Recital)，ePR係特別化(particularise)和補充GDPR所制定的個人資料規則(provisions)，將GDPR的原則轉化為具體規則。而此次草案著重於ePR第6條、第8條和第10條：

第6條：允許處理 (Permitted processing)

該草案引入「進一步兼容處理電子通信後設資料(metadata)」的可能性，建議擴大法規範圍，允許處理某些類型的後設資料用於研究，

避免扼殺科學研究和創新。借鑒GDPR第6條第4項，草案建議ePR 「更加面向未來」(more future-proof)，為快速變化的數位環境（如人工智能和物聯網）的發展提供靈活性。

第8條：保護最終用戶的終端設備信息(terminal equipment information)

第8條涉及最終用戶設備數據的儲存和處理(processing)，其側重於保護用於傳輸電子通信的設備。ePR試圖透過更新第二十段前言以闡明第8條的意旨，放寬對使用cookie等識別碼(identifiers)的限制。

第10條：隱私設置

草案建議刪除ePR第10條和各別的前言部分－要求軟件提供商(software providers)在每次更新隱私設置時通知最終用戶。幾個成員國基於以下理由質疑本條的價值：


	對最終用戶和創新業務的潛在影響；
	競爭問題；
	可能給瀏覽器和應用程式帶來負擔；
	潛在的最終用戶對於不斷的同意容易產生疲勞狀態；
	對遵守義務所能帶來的價值感到懷疑；
	對裁罰感到不安。

</description><pubDate>Thu, 22 Nov 2018 00:00:00 GMT</pubDate></item><item><title>【其他關聯議題】美國COIN CENTER發布加密貨幣證券法規框架第二版</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=62</link><description>美國研究去中心化科技及加密貨幣之機構Coin Center於2018年8月10日發布加密貨幣證券法規框架(Framework for Securities Regulation of Crytocurrencies)第二版研究報告（下稱系爭報告），作者Peter Van Valkenburgh為該機構研究主任(Director of Research)。系爭報告呈現美國有關加密資產(cryptographic asset)、加密貨幣(crytocurrencies)和代幣(token)的證券法規框架，包含比特幣(Bitcoin)、以太坊(Ethereum)及衍生產品專案(derivative Projects)等，該框架是立基於用來判斷投資契約(investment contract)的Howey Test，以及潛在的證券法規政策目標。

該研究報告指出於代幣專案的軟體及營運維護軟體的社群中，有三項關鍵變數(variable)：分散性(distribution)、去中心化(decentralization)及功能性(functionality)。為了創造用來判斷加密貨幣是否類似有價證券且應否受管制的框架，本報告更深入解釋三項變數並標記於Howey Test的四項要素中。根據系爭報告研究，大型且去中心化程度較高的代幣專案──譬如比特幣，或是功能性分散式運算服務(decentralized computing services)──譬如以太坊，較不容易符合有價證券的定義，也不存在證券法規的投資者風險；但有些較小型的代幣符合有價證券的定義。系爭報告也討論代幣的預售(pre-sales)的方式可能被視為有價證券發行，即便最終代幣生成及後續的代幣交易也不會從證券法規中受益。
</description><pubDate>Fri, 12 Oct 2018 00:00:00 GMT</pubDate></item><item><title>【其他關聯議題】加拿大證券管理委員會發布聲明稿，釐清代幣發行於證券法之適用疑義</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=61</link><description>加拿大證券管理委員會因應貨幣或代幣之發行於正券交易法之適用疑義，於2018年6月11日發布CSA Staff Notice 46-308聲明稿，處理有關代幣發行於證券法之適用疑義。本聲明稿說明先前之聲明CSA Staff Notice 46-307 Cryptocurrency Offerings (SN 46-307)已表示首次代幣眾籌（ICO或ITO）可能涉及證券之交易。此乃首次代幣眾籌含有投資契約，故這些產品可能被視為金融衍生產品（derivative）。此外，本聲明稿亦說明所謂代幣（utility token）係指具有單一或複數之特定功能，如可供持有者透過區塊鏈科技取得或購買服務或資產，並指稱本聲明稿係為處理以下兩者有關代幣發行之情形：


	當代幣之發行可能或未有涉及證券之發行
	當代幣之發行係透過數個步驟所組成


本聲明稿臚列出如何判斷代幣之發行究竟是否認屬投資契約之參考標準，並提出舉例供投資人留意，如該發行是否涉及金錢之投資、是否有期待利益、是否涉及他人之貢獻。根據證券管理委員會之經驗，許多稱為「代幣」（utility token）之代幣發行，往往都涉及投資契約，並強調代幣之功能（utility）並不單方面影響該代幣之發行是否應認屬證券之判斷。部分代幣之發行係於加密交易之交易平臺運作，如去中心化、P2P之區塊鏈平臺，然對於平臺或二級市場之控制力或影響力並不影響此代幣是否認屬證券之判斷。

本聲明亦指出，當代幣之發行係透過數個步驟所組成時，即便該代幣具有特定功能，該購買人於第二或第三步驟取得之代幣仍可能被視為證券，因該代幣已具有類證券之性質，如利潤共享。據此，發行人即應遵守證券相關之法規。
</description><pubDate>Mon, 10 Sep 2018 00:00:00 GMT</pubDate></item><item><title>【其他關聯議題】數位商務商會公告數位代幣指南，提出市場概要與政策、執行者之指導原則</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=60</link><description>於2014年7月19日在美國華盛頓特區成立的比特幣行業利益的貿易協會─數位商務商會（Chamber of Digital Commerce），於2018年7月30日公告第一版「數位代幣指南：市場概要與政策和執行者之指導原則」（Understanding Digital Tokens: Market Overviews &amp;amp; Guidelines for Policymakers &amp;amp; Practitioners）。該指南列出三大重點：1. 法規面：自美國、加拿大、澳洲、英國和直布羅陀之立法政策分析現行有關代幣之法制環境和相關之證券交易法；2. 代幣之原則與指導：提供企業和交易平臺就代幣之指導原則；3. 代幣之經濟規模：綜觀全球代幣之經濟、資訊和統計數據。

該指南列出現今多數國家多達成共識的Howey Test，用以判斷代幣究竟是否認屬投資契約（investment contract），而因此須遵守證券交易相關法規。此外，該指南亦列出企業針對代幣資訊負有揭露義務，如技術說明、企劃說明、代幣結構、分布與價格說明、風險揭露、行銷方式，以及個案研究報告等。該指南之建議值得作為各國就代幣規管之立法參考。
</description><pubDate>Fri, 10 Aug 2018 00:00:00 GMT</pubDate></item><item><title>【共享經濟】芬蘭新修正之交通法使Uber得以合法營運</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=59</link><description>芬蘭交通部因應交通之數位化和新興的營運模式，故於2017年5月24日發布新聞稿公告新修正之交通法規（Act on Transport Services） ，預告新修法會如期於2018年7月1日正式施行。芬蘭交通部說明，新修正之法規將促進交通市場之公平競爭性，並創造更有效率的交通法規框架 。Uber自在芬蘭停業一年後，因應芬蘭最新交通法修正，已於2018年7月4日重新營運，於各大城市如Helsinki、Espoo、Vantaa和Kauniainen等啟動UberX和UberBLACK服務。事實上，Uber司機本來因皆握有計程車駕駛執照，自屬合法，但因芬蘭政府根據舊的交通法規而限定每年得核發之計程車許可證照數量，並設有車資計算限制，故始得Uber多次遭到檢舉 。為此，芬蘭政府重新審視其交通法規，調適Uber此類共享交通得以營運之法規環境，而使Uber得以捲土重來。

然而，因應歐洲法院於2017年12月認定Uber是運輸服務公司之判決，將Uber之營運模式認定落入現行計程車業規管之範圍，故Uber將不會於芬蘭重新啟動UberPOP之營運模式，畢竟UberPOP並未與取得計程車駕駛執照之司機合作，故暫不會於芬蘭營運，避免觸法。
</description><pubDate>Mon, 09 Jul 2018 00:00:00 GMT</pubDate></item><item><title>【其他關聯議題】國際貨幣基金組織公告衡量數位經濟報告，檢討數位經濟之影響並提出建議</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=58</link><description>國際貨幣基金組織（International Monetary Fund）於2018年2月28日公告衡量數位經濟報告（Measuring the Digital Economy），係在評估數位經濟對當代社會的影響，並檢討現行法體系、法規範與組織無法確實呈現數位經濟的貢獻。此外，平均物價指數（GDP）因缺乏具數位經濟特質的產品和服務的類別，致使與GDP相關之數據統計欠缺真實性。

首先，該報告指出，以往對於數位經濟的想像多集中在網路平臺上的服務和交易，但事實上數位經濟的範圍應更為廣泛，甚至包含任何使用數位資訊的活動都應列為數位經濟的範疇。接著，該報告檢討GDP與福利制度的關聯，並說明數位經濟中的數位服務所帶來的「附帶」福利不應被忽略，如網路使用者於網路上自願參與的活動所帶來的附加價值。以電子商務而論，物價指數的計算往往都忽略網路零售業之標價，共享經濟中服務提供者對消費者所產生的價值亦。該報告以Airbnb為例，指出共享住宿對於觀光產業之提升、房地產市場之影響，以及稅賦的收入等多未有完善的追蹤與紀錄，共享交通如Uber亦使勞動市場不再透明。又，該報告指出數位經濟所帶來的全球化經濟已超越地理位置的限制，GDP以國家領土作為基準的計算方式應被審慎檢討。

綜上所述，因應數位經濟，該報告認為國際間應加強檢討並定期更新與數位經濟相關之定義、類別與技術機制，並透過國際協定達成一致。國家級的統計機關應被授權獲得更多數位資訊的資源與管道，以加強數位資訊之應用。此外，GDP應透過法制或政策數位化，並免無法有效呈現數位經濟的全貌。
</description><pubDate>Thu, 28 Jun 2018 00:00:00 GMT</pubDate></item><item><title>【其他關聯議題】新加坡衛生部將啟動醫療沙盒制度，鼓勵遠距醫療創新應用</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=57</link><description>因應健康保險環境建置變動快速，並加強病患權益與支持健保改革，新加坡衛生部（Ministry of Health）於2018年4月18日啟動認證實驗和調適機制（Licensing Experimentation and Adaptation Programme, LEAP），即為俗稱的醫療沙盒。衛生部表示，初次階段將以遠距醫療（telemedicine）服務作為首次應用類型，以適行新興且創新的健保服務。衛生部將公告限制條款、政府資料運用和風險降低策略等。衛生部補充，病患將可因LEAP制度而提早自新興的健保模式受益，同時可確保相關安全和風險無虞，後續病患和遠距醫療的業者亦可自實驗結果受惠。又，衛生部可透過LEAP制度而與醫療相關的新創業者接軌，了解最新服務應用與法規適用狀況，以便適時進行相關法規範調適。最重要的是，採用醫療沙盒制度之業者最終將經政府核准而得合法營運。

衛生部說明，未來將針對遠距醫療採用風險導向的審核機制，鼓勵直接提供醫生與病患間的診斷服務。目前預計參加醫療沙盒之業者為WhiteCoat和RingMD，該些業者於進行LEAP制度時會標注監理沙盒標章（Regulatory Sandbox logo），供服務使用者辨識。
</description><pubDate>Tue, 08 May 2018 00:00:00 GMT</pubDate></item><item><title>【電子商務】英屬直布羅陀公告代幣法規，將完善代幣發行、銷售、投資服務等規範</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=56</link><description>英國海外屬地直布羅陀於2018年3月13日公告代幣法規（Token Regulation）以及有關首次代幣發行（initial coin offering）之規範。該法規設定直布羅陀金融服務委員會（Gibraltar Financial Services Commission, GFSC）為主管機關，授權並監管第二代幣市場之營運者，並建立營運者之公開登記系統。此外，該委員會將規範代幣投資建議，如商品相關之建議、個人投資建議等。又，該法規認定代幣非屬歐盟法或直布羅陀法下之證券（securities），且代幣僅代表持有者先行就未來網絡或消費者服務進行商品交易，故僅可認屬商品，而非證券。該法規公告官方授權監管體制，要求每一位進行首次代幣發行之發行者於直布羅陀進行買賣或發送代幣時，應指派特定人監管其銷售以確保符合法規。

直布羅陀財務中心（Gibraltar Finance Centre）和直布羅陀金融服務委員會表示授權監管體制之實施係以市場作為導向之ICO規範，避免掛一漏萬的立法漏洞。該體制會以市場作為標準認定何謂「優良」的代幣，而非以監管者的角度出發。直布羅陀政府於該代幣法規中說明，政府預計於2018年3月底完成法案草擬，有關代幣之行銷、銷售和發送之法規則預計於2018年5月完成。其他三項法規另預計於2018年10月底完成。
</description><pubDate>Tue, 10 Apr 2018 00:00:00 GMT</pubDate></item><item><title>【電子商務】美國懷俄明州可望通過新法，鬆綁功能代幣於證券、貨幣傳輸與稅法等限制</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=55</link><description>美國懷俄明州眾議院（Wyoming House of Representatives）於2018年2月19日無異議地表決通過HB0070法案，該法案將鬆綁功能代幣（utility token）於懷俄明州證券法（Securities Act）之限制。根據立法歷程，該法案將送往參議院，若順利通過，並經州長簽署核准，將於2018年7月1日生效，使懷俄明州成為友善的區塊鏈投資環境，預計吸引大量新創事業於該州進行首次代幣眾籌（Initial Coin Offerings, ICO）。;

該法案針對功能代幣設有三種要件，僅於符合三種要件者使能作為法案所稱的功能代幣，而得免受證券法規管。三種要件分別為：一、功能代幣之開發者和發行者不得將代幣作為投資而行銷；二、該代幣須可作為換取商品或服務之對價；三、該代幣之開發者或發行者不得主動進行附買回協議（repurchase agreement）或任何有意操縱代幣二級市場之價格之協議或策劃。

此外，懷俄明州另有三部有關區塊鏈之法案亦正待審議，包含同樣甫經眾議院通過之HB0019法案，使加密貨幣免受懷俄明州貨幣傳輸法（Money Transmitters Act）規範，有望可使加密貨幣在懷俄明州進行交易或交換。此外，正於眾議院進行二審的HB0101法案預計將修正懷俄明州商業公司法（Business Corporations Act），開放公司得使用區塊鏈來儲存資料並進行內部聯繫。又，尚待眾議院審議的SF0111法案預計使加密貨幣免於受州財產稅法之規範。
</description><pubDate>Tue, 13 Mar 2018 00:00:00 GMT</pubDate></item><item><title>【電子商務】英國開放銀行計畫於2018年1月13正式施行</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=54</link><description>因應於2018年1月13日上路的歐盟法案「第二號支付服務指令（The second Payment Services Directive，PSD2）」，其要求銀行於獲得客戶授權後，得開放第三方存取客戶帳戶數據，並能直接自客戶的銀行帳戶扣款，而不需透過刷卡。英國競爭及市場管理局（Competition and Markets Authority）於2018年1月13正式施行開放銀行計畫（Open Banking）。

開放銀行計畫係起源於英國競爭及市場管理局於2016年調查消費者銀行，提出報告並指出現階段銀行對於小型或新型銀行的阻礙降低了銀行的競爭力。因此，該局提出了開放銀行計畫，要求銀行在經客戶同意之後，應分享客戶的金融資訊與其他金融機構。該計畫係本於此作法將有效可根據客戶的消費習慣，提升金融商品之客製化和流通性。此外，客戶將可因為跨金融機構之資訊流通，而可透過一站式服務掌握所有銀行帳戶的明細。此計畫主要係為轉型傳統銀行對於消費金融之管理，鼓勵朝向開放資源、開放原始碼的商業模式，並藉由金融資訊的流通，促進數位金融新創的機會，進而使傳統大型銀行採用新科技以利轉型。本計畫可視為英國為因應PSD2指令和數位金融的來臨而提出的轉型策略。
</description><pubDate>Tue, 27 Feb 2018 00:00:00 GMT</pubDate></item><item><title>【共享經濟】阿姆斯特丹市政廳預計自2019年起將短期私宅出租之每年累積日數自60天縮短為30天</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=53</link><description>阿姆斯特丹曾於2013年6月通過Airbnb友善法（Airbnb-friendly law），針對短期私宅出租創設新類別之私人出租（Private Rental），允許居民得以間斷性地出租其自用住宅，但屋主需同住於內，需經登記，且期間以每年最多60天為限，每次最多四人限制出租自宅。然而，阿姆斯特丹市政廳預計自2019年起將60天縮短為30天，且仍需經登記，且一次至多僅得出租予四人。阿姆斯特丹執行委員會（city&amp;rsquo;s executive board）於2017年1月10日表示支持此政策。

針對此政策上之改變，Airbnb表示相當失望，且說明此變動將有利於飯店，並影響當地居民的權益。Airbnb表示，阿姆斯特丹因為Airbnb而於2015年至2016年間課徵一千一百萬歐元之觀光稅，若採用新政策，將對當地的經濟造成衝擊。此外，報載於2017年期間至少有六千件違規事件，其中五千件為長期永久出租私宅，但Airbnb反駁此數據，宣稱僅有一千件。在違規事件數如此高的情形下，殊難想像阿姆斯特丹市之新政策上路後，該如何確保屋主遵循法規。
</description><pubDate>Tue, 30 Jan 2018 00:00:00 GMT</pubDate></item><item><title>【個資保護/資訊安全】美國參議院議員聯手提出終止違反本人意願線上使用者圖像騷擾法案，擬以聯邦位階遏止情色報復</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=52</link><description>繼美國加州第114屆國會選區眾議院議員Jackie Speier於2016年7月中旬提出私密隱私保護法案(Intimate Privacy Protection Act, IPPA)後，由於該法案僅停留於美國眾議院，未能至美國參議院。是故，參議院議員Kamala D. Harris、Richard Burr、Amy Klobuchar和眾議院議員Jackie Speier再度攜手合作，提出終止違反本人意願線上使用者圖像騷擾法案（Nonconsenual Online User Graphic Harassment (ENOUGH) Act of 2017），提倡本法將以聯邦位階，有效遏止違反本人意願散布本人的身體私密影像之惡性持續蔓延。

該法案要求法務部應有相應的工具處理這類騷擾案件，且對於分享該影像的使用者課予聯邦刑事責任。然而，若需根據該法案起訴，則檢察官須證明行為人知悉被害人預期該影像為私密，且知悉分享的行為將傷害被害人。此外，檢察官須證明無任何理性之人會預期該影像將觸及公共利益。本法案受到兩黨的支持，且如科計巨擘Twitter和Facebook也表態支持。眾議院議員Jackie Speier更強調，即便目前有許多州刑法已有類似的規定，但被害人幾乎無資源提起訴訟，遑論尚無入罪化之州別，被害人即使鼓起勇氣提起訴訟仍求償無門，故有迫切通過本法案之必要。
</description><pubDate>Tue, 19 Dec 2017 00:00:00 GMT</pubDate></item><item><title>【共享經濟】亞利桑那州於2017年1月1日正式施行全面合法化共享短期住宿之新法案</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=35</link><description>2016年5月13日，亞利桑那州州長Doug Ducey簽署共享短期住宿新法案SB1350，該法案於2017年1月1日正式施行，為美國首次完全開放共享短期住宿的法案。根據州長Doug Ducey之說法，乃希望讓亞利桑那州成為共享經濟之州，並預期可吸引觀光潮，讓當地居民可以直接受益於觀光客的經濟效益。

;

該法案規定，州政府轄下的所有城市皆不得僅因經營短期住宿業者之地點未登記為飯店而禁止經營短期住宿，換言之，Airbnb和HomeAway等業者皆可自由地提供房東登載短期住宿服務。亞利桑那州共享短期住宿的新法案允許房東提供臥房的短期住宿，甚至是整個房屋的短期住宿，對房地產出租數量和住宿期間毫無限制，整個社區甚至都能成為度假用的短期住宿區。

;

此外，透過合法化，新法案亦規定提供短期住宿平臺之業者可協助蒐集並繳納5.5%的稅賦，直接從房客的帳單中扣繳，並由平臺經營業者蒐集和繳納予亞利桑那州稅務部(Arizona Department of Revenue)。經營短期住宿的房東利用原居住用的房地產，即便經營短期住宿，仍採用居住型財產稅率(Residential Property Tax Rate)。如此，不僅共享短期住宿不再會有逃漏稅的爭論，對政府、房客和房東而言亦能減少許多時間和成本負擔。
</description><pubDate>Thu, 23 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【共享經濟】歐盟法院將開庭定UBER服務性質</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=34</link><description>歐盟法院於2016年11月29日由最高法院開庭審理UBER案，本案將決定UBER於歐盟區域範圍內的服務性質，而交通運輸服務(transport service provider)或資訊平台服務(information society service provider)，甚或綜合服務的性質判斷，也將影響UBER日後於歐盟應遵守之法律規定。

;

UBER 2012年開始於歐盟區域提供共乘服務，遭遇歐盟會員國當地政府、運輸服務業者反對聲浪(2014年西班牙禁止UBER營運；2016年法國各地計程車公會對UBER進行抗議遊行，同年法國政府認定UBER為非法交通營運，判處罰鍰)，擔心UBER不受當地運輸服務業者安全規範等約束，會造成不公平競爭。

;

UBER於本案主張其性質為資訊平台服務提供業者，並認為UBER共享經濟的目標與歐盟減少歐洲各國交流壁壘之宗旨一致，在網際網路統一市場上，將有助減少歐洲市場壁壘。判決預計於2017年作成。
</description><pubDate>Thu, 23 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【共享經濟】加拿大漢米爾頓市有望擬通過新法合法管制網路叫車平臺</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=33</link><description>加拿大安大略省漢米爾頓市（Hamilton）於2017年1月18日通過新法，要求網路叫車平臺，如Uber，需有如同計程車的保險機制，並規定車輛應有可識別網路叫車平臺公司之要求。此外，漢米爾頓市會有目前將近900筆Uber司機之資料庫，確保司機皆屬合法，並禁止網路叫車平臺的司機於路上隨行接受招纜生意，減少網路叫車平臺的營運風險，並加強大眾運輸的公共安全。

;

該法更規定，Uber應每年繳交5萬美元的年費，並按每次旅程的6%繳交稅賦。市政府更會有專職人員處理網路叫車平臺的執照管理，該稅收將可預期為市府增進每年11萬美元的收入。另一方面，為保障傳統計程車行業，漢米爾頓市政府將調降計程車的營運年費，由194美元調降為100美元，並僅限傳統計程車司機可於路邊人行道處招攬生意。目前該法案待2017年1月25日由市議會同意簽署，一旦通過，就正式成為市府法規。
</description><pubDate>Thu, 23 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【電子商務】中國人大第25次會議首次審議電子商務法草案</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=32</link><description>中國全國人民大表大會12月19日舉行第12屆全國人大常委會第25次會議，首次審議電子商務法草案。該草案共8章94條，內容主要包括：

1. 明確電子商務定義，如電子商務、信息網路、商品交易、服務交易、經營活動等；

2. 區分一般電子商務經營者與電子商務第三方平台，並著重對第三方平台之規定(規劃經營者審查機制、要求公開、透明交易原則、遵循記錄保存等要求，以及提供退場機制等)；

3. 明確對於電子合同、電子支付和快遞物流三方保障，鼓勵數據信息交換共享，強調用戶個人信息採取相應保障措施，以促進數據信息合法、合理利用；

4. 設專章對跨境電子商務活動進行規範，由國家推動建立監督管理體系，並電子化電子商務通關、稅收、檢驗檢疫等通關環節，促進貿易便捷。

19日國務院發佈《「十三五」國家戰略性新興產業發展規劃》也提出「加強相關法律法規建設」，要求針對互聯網與各行業融合發展的新特點，調整不適應發展要求的現行法規及政策規定，與電子商務法草案之提出相呼應。
</description><pubDate>Wed, 22 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【個資保護/資訊安全】PDPC發布、修訂個人資料電子媒介保護指南和個人資料物理上處理指南</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=31</link><description>新加坡個人資料保護委員會（PDPC）發布一份新指南「個人資料時防止意外披露指南」(Guide to Preventing Accidental Disclosure)，為組織提供在處理和發送個人資料時防止意外洩露的知識，提供以下指導：


	&amp;lt; &amp;gt;&amp;lt; &amp;gt;&amp;lt; &amp;gt;&amp;lt; &amp;gt;&amp;lt; &amp;gt;
	PDPC並更新「個人資料電子媒介保護指南和個人資料物理上處理指南」(Securing Personal Data in Electronic Medium and Guide to Disposal of Personal Data on Physical Medium)，為組織處理個人資料的提供新的示例做法。
	「中小企業網站建置指南」(The Guide on Building Websites for SMEs)還更新了一個關於使用現成軟體的新章節，建議組織了解軟體的功能，以及如何配置以處理個人資料。;
	

</description><pubDate>Thu, 23 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【個資保護/資訊安全】日本擬於2018年推動AI安全認證</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=30</link><description>日本從去年(2016)開始，積極投入人工智慧(AI)領域。總務省、文部科學省和經濟產業省於2016年4月成立「人工智能技術戰略會議」由政府主導人工智慧研發，其下並設立研究協作會議以及產業協作會議，加速AI技術研發及成果應用。此外，內閣並於2016年5月設立「人工智能與人類社會理事會」探討AI與人類社會之關係，旨在促進人類社會發展。2016年6月總務省提出「人工智慧(AI)網路化研討會」期中報告以及「AI網路化影響與風險」報告，展望AI發展下的社會型態，分析AI網路化後的影響、風險還有待解決問題，如涉及個人資料之隱私問題、資通訊基礎設施完備、AI網路的治理等。

;

因為存在上述問題，且AI也一直有人類社會安全疑慮，日本政府準備研擬AI安全認證，規範所有內建AI的產品、機器人，已確保使用者安全，建立社會大眾對AI的信賴，預計於2018年開始推行。總務省將成立認證單位，審查AI技術，同時要求意外事件發生時的AI反應邏輯。總務省也將針對事件發生之責任歸屬、風險控管等，進行研究。
</description><pubDate>Thu, 23 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【個資保護/資訊安全】歐盟執委會發布最新資料經濟策略通知</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=29</link><description>歐盟執委會於今年1月10日發布「歐洲資料經濟建構通知」(Communication on building a European data economy)。「通知」以2014年「資料驅動經濟通知」(Communication on data-driven economy)為基礎，重點討論資料跨境傳輸與資料在地化議題。

此外，「通知」歸納新興資料科技發展下所衍生之法律議題，包括：

1. 與個人無關之自動化資料之近用、傳輸；

2. 資料法律責任；

3. 非個人資料之可攜性(portability)、共用(interopability)與標準。

歐盟資料經濟之發展，據2015年統計，已達2720億歐元之規模，發展領域涵括健康、食品安全、氣候、節能、智慧交通與智慧城市等，歐盟將持續針對重點領域，尋求資料經濟的發展機會。
</description><pubDate>Thu, 23 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【個資保護/資訊安全】歐洲雲端處服務業者祭出新資料保護規定</title><link>https://www.vtaiwan.org.tw/international_detail.aspx?no=211&amp;d=28</link><description>歐洲雲端基礎服務企業聯盟(CISPE)2017年1月提出「雲端基礎服務業者資料保護行為準則」(Data Protection &amp;ndash; Code of Conduct for Cloud Infrastructure Service Providers)，要求業者如處理雲端消費者個人資料，遵循行為準則之嚴格要求。準則除更細緻提供業者歐盟GDPR等相關法令遵循外，明確定義業者之資料安全責任，同時要求提供雲端消費者資訊自主空間，讓消費者得以要求儘於歐洲經濟區內(European Economic Area, EEA)處理、保存其個人資料。

行為準則將可提供歐洲雲端消費者一判斷之參考方向，評估業者處理個人資料時是否採取適當安全措施。
</description><pubDate>Thu, 23 Feb 2017 00:00:00 GMT</pubDate></item></channel></rss>