<?xml version="1.0" encoding="utf-8"?><rss version="2.0" xmlns:blogChannel="http://backend.userland.com/blogChannelModule"><channel><title>臺灣個人資料保護與管理制度</title><link>https://www.vtaiwan.org.tw</link><description>最新消息</description><copyright>Copyright © 經濟部商業司 All Rights Reserved. 經濟部商業司廣告 </copyright><generator /><item><title>【網站公告】《跨部門資料運用線上諮詢會議》將於10/31舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=88</link><description>為提早蒐集更多想法和建議，vTaiwan並開啟Pol.is作為線上意見徵集的管道，歡迎關心本議題的朋友可以先到網頁上發表自己的想法和建議，並可針對別人的想法和建議進行投票。vTaiwan作為網路社群，對於公開資料和跨部門資料運用非常關心，故將於2018年10月31日晚間七點至九點，再開線上諮詢會議，協助釐清跨部門資料運用之議題。歡迎網友實際現身報名參與，或也可直接在臉書粉絲頁上收看直播！


</description><pubDate>Tue, 16 Oct 2018 00:00:00 GMT</pubDate></item><item><title>【活動公告】《談網路內容之管制措施直播焦點座談會》將於10/17舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=87</link><description>台灣陸續出現各家不同的草案版本，共同的目標都是為解決身體私密影像不當遭外流，及該如何保障被害人的權益和後續救濟。對於此一高度仰賴社會共識的議題，vTaiwan 與女人迷#CodeforGender合作，在今年9月啟動線上問卷，傾聽網友的經驗、對身體私密影像的看法。vTaiwan作為網路社群，為能提供各家提供草案的單位更多網路使用的實際經驗，以及對於網路言論自由和個人隱私之想法與建議。將於10月17日晚上19點00分召開《談網路內容之管制措施直播焦點座談會》，邀請公協會及公民團體，一同探討以作為後續法制參考。歡迎有興趣的網友線上收看直播，請各位夥伴千萬不要錯過！


</description><pubDate>Tue, 16 Oct 2018 00:00:00 GMT</pubDate></item><item><title>【活動公告】《政府資料跨部門運用之法制研析─民間資料如何進入政府部門決策系統之探討》直播焦點座談會將於8/30舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=86</link><description>公部門向私部門尋求合作之模式即「群眾外包」(Crowdsourcing)，係指透過網路串連一群人，獲取他們的知識、專長、時間以及資源的過程，往往是公益或互助性質居多，成果也多半是社群內共享，或者是開放給大眾使用，透過這種合作模式，開啟政府與民間共同聚焦在問題導向的解決模式。惟伴隨私部門之資料進入公部門之決策系統，可能遭逢些許風險，如當資料有誤時應向何方究責、資料是否偏頗、公部門與私部門資料之運用是否符合政府採購法等等爭議。為擴大或鼓勵政府與民間資料交換之策略，達到政府跟民間資料共享。爰此，特舉辦本次座談會，檢視民間資料進入政府決策機制之時機點，並探討如何降低政府使用民間資料之風險，作為本研究後續提出相關法制建議之參考。將於8月30日下午14點30分召開《政府資料跨部門運用之法制研析─民間資料如何進入政府部門決策系統之探討》直播焦點座談會，邀請專家學者、公協會及公民團體，一同探討以作為後續法制參考。歡迎有興趣的網友線上收看直播，請各位夥伴千萬不要錯過！
</description><pubDate>Tue, 28 Aug 2018 00:00:00 GMT</pubDate></item><item><title>【活動公告】《政府資料跨部門運用之法制研析─政府資料公開之議題研析座談會》直播焦點座談會將於8/22舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=85</link><description>為推動行政院及所屬各級機關政府資料開放，結合民間資源及創意，達成施政便民及公開透明之目的，行政院訂有「行政院及所屬各級機關政府資料開放作業原則」，作為政府機關開放資料原則性約定，即將被動申請公開資料轉換為主動公開資料集的作法。惟前開作業原則施行迄今，是否足以滿足民間取得政府資料之需求，亦有探討檢視之必要。為擴大或鼓勵政府資料釋出之策略，爰此，特舉辦本次座談會，期能蒐集民間對於政府開放資料之需求，以檢視目前政府資料釋出作法之缺漏，作為本研究後續提出相關法制建議之參考。將於8月22日上午10點30分召開《政府資料跨部門運用之法制研析─政府資料公開之議題研析座談會》直播焦點座談會，邀請專家學者、公協會及公民團體，一同探討政府資料公開之法制研析，以作為後續法制參考。歡迎有興趣的網友線上收看直播，請各位夥伴千萬不要錯過！
</description><pubDate>Wed, 15 Aug 2018 00:00:00 GMT</pubDate></item><item><title>【活動公告】《政府資料跨部門運用之法制研析》於2018/03/21至2018/04/21進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=84</link><description>在討論個資專責機關的同時，是否也須同時思考資料究竟該如何在政府與民間運用？本問卷係由國家發展委員會委託國巨律師事務所執行「政府資料跨部門運用之法制研析案」，其目的藉由本問卷蒐集大家對於政府資料跨機關資料共享(如財稅資料提供給其他機關使用)、開放釋出、擴大公私部門整合服務之議題意見，以作為法制調適之建議。本議題將進行線上意見徵集，期間為一個月，歡迎大家踴躍參與並分享您的寶貴意見！
</description><pubDate>Thu, 22 Mar 2018 00:00:00 GMT</pubDate></item><item><title>【活動公告】《無人載具科技創新實驗條例》於2017/12/8至2017/12/13進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=83</link><description>本次新訂實驗條例，期為建置適當機制及法規環境，鼓勵各界積極投入無人載具科技創新實驗，除為推行創新政策所必須，亦為外界所殷切期盼。為使立法效益儘早實現，並儘速解決目前無人載具在開放、公共環境測試時無法可管之實務狀況，爰縮短公告期間，公告14日，歡迎大家踴躍參與並分享您的寶貴意見！
</description><pubDate>Tue, 19 Dec 2017 00:00:00 GMT</pubDate></item><item><title>【活動公告】《個資與隱私保護專責機關》於2017/11/08至2017/12/08進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=81</link><description>不同於多數國際立法例，我國定有個人資料保護法，但各目的事業主管機關於適用個資法時偶有出入，為統一個資法適用的法律爭議，未來似應可考量設立個資與隱私保護的專責機關。本議題將進行線上意見徵集，期間為一個月，歡迎大家踴躍參與並分享您的寶貴意見！
</description><pubDate>Thu, 09 Nov 2017 00:00:00 GMT</pubDate></item><item><title>【活動公告】《醫師、心理師透過網路平台提供服務》線上諮詢會議將於10/26舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=80</link><description>　　為了解現行法制是否可配合適用即有重新思考、檢視之必要，提供醫療及心理諮商業者可持續發展、創新突破之產業環境，並調適相關法規範，以解決法規適用爭議，10月26日晚間7點將召開線上諮詢會議，邀請專家和實務工作者共同討論醫師、心理師透過網路平台提供專業服務之重要議題，歡迎有興趣的網友隨時加入討論，請各位夥伴千萬不要錯過！


</description><pubDate>Wed, 18 Oct 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】《因應平台經濟發展法規調適參考原則草案》於2017/9/20至2017/10/20進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=79</link><description>共享經濟繼2017年5月至8月間完成兩階段之意見徵集，並於8月17日召開線上諮詢會議後，國發會參考相關意見及歐盟2016年「協作經濟議程」，調整原共享經濟議題範圍至平台經濟，擬具「行政院所屬各機關因應平台經濟發展法規調適參考原則」，並進行第三階段之意見徵集，本次期間同樣為一個月，歡迎大家踴躍參與並分享您的寶貴意見！
</description><pubDate>Thu, 21 Sep 2017 00:00:00 GMT</pubDate></item><item><title>【活動公告】《遙控無人機應用與管理機制》線上諮詢會議將於9/21舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=78</link><description>　　為利後續「遙控無人機管理規則」之訂定，並符合實需，9月21日晚間7點將召開線上諮詢會議，與專家和實務工作者共同討論共享經濟重要議題，包含：無人機定位管理技術、人員學術科操作證測驗標準，以及農業應用等，歡迎有興趣的網友隨時加入討論，請各位夥伴千萬不要錯過！


</description><pubDate>Tue, 12 Sep 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】《無人載具科技創新實驗條例》於2017/9/7至2017/10/7進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=77</link><description>國際間發展無人載具，主要以無人車輛為發展重點，其中又可區分為商業運輸車輛與個人私有車輛。商業運輸車輛發展目前以自動駕駛化為主，如自動駕駛巴士、自動駕駛貨車，利用自動駕駛車輛降低營運成本並提升運輸效率。個人私有車輛發展目前以駕駛輔助為主，透過系統輔助降低駕駛人行車疲勞並提升行車安全。國際間各類車輛為求符合實際道路使用需求，已陸續走出實驗場域，於各地區進行公共道路實地測試。為了解一般大眾對自駕測試的想像及感受，歡迎大家提出各種想法和意見！
</description><pubDate>Thu, 07 Sep 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】《醫師、心理師透過網路平台提供服務》於2017/8/30至2017/9/30進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=76</link><description>平台經濟已為全球商業發展主要趨勢，透過網際網路提供民眾、消費者各種實體產品或服務，其中並包含透過網路平台提供醫療及心理諮商等專業服務之平台業者，亦乘此風潮蜂擁崛起。為了解民眾對於網路提供醫療服務的需求與管制建議，歡迎大家踴躍參與並分享你的寶貴意見！
</description><pubDate>Fri, 01 Sep 2017 00:00:00 GMT</pubDate></item><item><title>【活動公告】《違反本人意願而散布本人的身體私密影像》線上諮詢會議將於9/14舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=75</link><description>為了解一般大眾對「身體私密影像」的想像，以及對「違反本人意願而散布」的感受和意見，歡迎大家一同參與討論及提供意見，並解決相關法規適用爭議。

9月14日晚間7點將召開線上諮詢會議，與專家和實務工作者共同討論「違反本人意願而散布本人的身體私密影像」，歡迎有興趣的網友隨時加入討論，請各位夥伴千萬不要錯過！


</description><pubDate>Fri, 25 Aug 2017 00:00:00 GMT</pubDate></item><item><title>【活動公告】《共享經濟重要議題之探討》線上諮詢會議將於8/17舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=74</link><description>為探討共享經濟創新商業模式，並解決相關法規適用爭議，8月17日晚間7點將召開線上諮詢會議，與專家和實務工作者共同討論共享經濟重要議題，歡迎有興趣的網友隨時加入討論，請各位夥伴千萬不要錯過！


</description><pubDate>Tue, 01 Aug 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】社會企業於2017/7/20至2017/8/19進行線上問卷調查！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=73</link><description>於2017/3/2進行線上諮詢會議後，社會企業經收斂議題與綜整意見，本次將更細部針對社會企業的具體內容進行線上問卷調查，歡迎大家踴躍填寫問卷並分享你的實務經驗！
</description><pubDate>Tue, 25 Jul 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】共享經濟於2017/7/5至2017/8/5進行第二次線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=72</link><description>共享經濟繼2017/5/24至6/24完成線上意見徵集後，回收問卷並收斂議題，本次將針對更細部且具體的內容進行共享經濟第二次線上意見徵集，歡迎大家踴躍參與並分享你的寶貴意見！
</description><pubDate>Thu, 06 Jul 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】無人機於2017/6/14至2017/7/14進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=71</link><description>無人飛行載具乃是指向藉由遙控或者自動駕駛技術，進行科學觀測及偵查等任務的飛行載具。與傳統飛機相比較，具有操作成本低、運用彈性大及支援裝備少等特性。民航局將在民用航空法中增訂遙控無人機專章，並在此之前，藉由vTaiwan平臺針對管理規範與執行方式進行討論。
</description><pubDate>Wed, 14 Jun 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】違反本人意願而散布本人的身體私密影像於2017/6/7至7/21進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=70</link><description>未經本人同意而散布本人身體私密影像的原因和方法有很多種，且造成本人名譽、生活等損害，應否加以處罰？以刑事、行政或民事處罰？我國現行法制是否完善？等等，均值得討論。為了解一般大眾對「身體私密影像」的想像，對「違反本人意願而散布」的感受，歡迎大家一同參與討論及提供意見。
</description><pubDate>Mon, 05 Jun 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】共享經濟於2017/5/24至6/24進行線上意見徵集！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=69</link><description>共享經濟（Sharing economy），又稱分享型經濟，是一種共用人力與資源的社會運作方式。它包括不同個人與組織對商品和服務的創造、生產、分配、交易和消費的共享。常見的型式有汽車共享、拼車、公共自行車，以及交換住宿等。與此同時，共享經濟又具有弱化擁有權，強化使用權的作用。在共享經濟體系下，人們可將所擁有的資源有償租借給他人，使未被充分利用的資源獲得更有效的利用，從而使資源的整體利用效率變得更高。
</description><pubDate>Mon, 05 Jun 2017 00:00:00 GMT</pubDate></item><item><title>【活動公告】公司法修法系列：社會企業線上諮詢會議3/2舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=68</link><description>
</description><pubDate>Fri, 17 Feb 2017 00:00:00 GMT</pubDate></item><item><title>【活動公告】企業資產擔保法草案線上諮詢會議將於1/20舉行！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=67</link><description>企業資產擔保法草案線上諮詢會議將於1/20舉行！本次意見徵集著重兩方面：首先，想瞭解大家對於企業資產擔保法必要性的想法，此外，也希望各界對於企業資產擔保法（草案）條文提出建議，歡迎大家線上或線下踴躍參與喔~
http://vtaiwanmeeting.kktix.cc/events/6037b31d-c5798a
</description><pubDate>Mon, 16 Jan 2017 00:00:00 GMT</pubDate></item><item><title>【網站公告】公司法社會企業意見徵集中！！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=66</link><description>近年來社會大眾對於企業的期待，已不僅止於追逐獲利，而是期望公司應善盡社會責任，並藉由商業手段，解決現今社會所面臨的食安、弱勢族群照護等問題。;然而，現行公司法是否容許社會使命型公司（兼益公司）之設立，甚或提供公司運作的基本框架，以鼓勵其發展並與國際趨勢接軌？均值得探究。歡迎大家至https://vtaiwan.tw/social-enterprise/init/

分享意見和經驗喔！！;
</description><pubDate>Tue, 20 Dec 2016 00:00:00 GMT</pubDate></item><item><title>【網站公告】企業擔保交易法（草案）跨部會意見徵集開跑！！！</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=65</link><description>企業擔保交易法（草案）跨部會意見徵集開跑！！！

國內公司經營環境是否提供足夠籌措資金管道？在鼓勵創新創業政策下，我國是否應推動企業資產擔保法？歡迎在vtaiwan分享您的經驗與意見~

https://vtaiwan.tw/securitization/
</description><pubDate>Wed, 14 Dec 2016 00:00:00 GMT</pubDate></item><item><title>【活動公告】數位經濟法規調適線上諮詢會議 Part 1</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=64</link><description>時間：105年11月10日19:00-21:00
主題：引進「公司英文名稱登記」制度

現行公司法及相關法規規定，公司名稱必須為中文，而外國公司在臺灣登記必須把公司名稱翻譯為中文，如IBM稱為「台灣國際商業機器股份有限公司」。從事進出口業務的公司雖然可以申請「出進口廠商英文名稱登記」，但該英文名稱並沒有公司名稱的保護效力。

近來各界建議政府，將「公司英文名稱登記」法制化，作為全球化商業活動及頻繁跨境交易之識別，「vTaiwan.tw」平台(https://vtaiwan.tw)就此議題已於8/14-8/31與9/23-10/23進行二階段意見徵集與討論，歡迎各界至「vTaiwan.tw」了解議題內容及討論情形。105年11月10日19:00-21:00將舉辦線上諮詢會議，邀集經濟部、學者專家與社群參與者，就此項議題進行討論。本次會議並將同步於「行政院開麥啦」進行直播，歡迎觀賞。

會議資訊以及相關資料將持續更新於vTaiwan網站，敬請上網查閱。
</description><pubDate>Thu, 03 Nov 2016 00:00:00 GMT</pubDate></item><item><title>【活動公告】數位經濟法規調適線上諮詢會議 Part 1</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=63</link><description>數位經濟法規調適線上諮詢會議 Part 1

時間：105年11月10日19:00-21:00
主題：引進「公司英文名稱登記」制度

現行公司法及相關法規規定，公司名稱必須為中文，而外國公司在臺灣登記必須把公司名稱翻譯為中文，如Microsoft稱為「台灣微軟股份有限公司」。從事進出口業務的公司雖然可以申請「出進口廠商英文名稱登記」，但該英文名稱並沒有公司名稱的保護效力。

近來各界建議政府，將「公司英文名稱登記」法制化，作為全球化商業活動及頻繁跨境交易之識別，「vTaiwan.tw」平台(https://vtaiwan.tw)就此議題已於8/14-8/31與9/23-10/23進行二階段意見徵集與討論，歡迎各界至「vTaiwan.tw」了解議題內容及討論情形。105年11月10日19:00-21:00將舉辦線上諮詢會議，邀集經濟部、學者專家與社群參與者，就此項議題進行討論。本次會議並將同步於「行政院開麥啦」進行直播，歡迎觀賞。

會議資訊以及相關資料將持續更新於vTaiwan網站，敬請上網查閱。
</description><pubDate>Thu, 03 Nov 2016 00:00:00 GMT</pubDate></item><item><title>【網站公告】vTaiwan 將在九月初擴大規模，新議題為金管會「監理沙盒」和「公司英文名稱登記」法制化</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=61</link><description>vTaiwan 將在九月初擴大規模、正式啟動。接下來的兩星期裡，我們想先請各界分享對「監理沙盒」議題的關注焦點，來協助金管會規劃出更符合期待的討論議題。

;

問卷網址：https://vtaiwan.tw/sandbox

延伸閱讀：〈沙盒裡一切平等！金融科技的創新監理〉
http://www.bnext.com.tw/column/view/id/40540

;

近來各界建議政府，將「公司英文名稱登記」法制化，作為全球化商業活動及頻繁跨境交易之識別。在九月初進入討論階段前，vTaiwan 籌備團隊想先瞭解各方對此議題關注的焦點。感謝協助！

;

問卷網址：https://bit.ly/vtaiwan-naming

說明簡報：http://www.slideshare.net/vtaiwan/ss-64981472
</description><pubDate>Mon, 22 Aug 2016 00:00:00 GMT</pubDate></item><item><title>【網站公告】零售業等網路交易定型化契約應記載及不得記載事項規範 新制說明暨產業意見交流座談 </title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=60</link><description>
網路購物買到瑕疵商品怎麼辦？網路上遇到的問題，有甚麼管道解決？消費者應如何參與、維護自己的權益？

因應推陳出新的電子商務模式，經濟部於今年(2016)7月修正公告了「零售業等網路交易定型化契約應記載及不得記載事項」，將舉辦臺北場、高雄場共2場的新制說明暨產業意見交流座談，竭誠歡迎共同參與、蒞臨指教!

</description><pubDate>Tue, 09 Aug 2016 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 11 ~ Part 14：數位匯流五法預計將於4月登場</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=59</link><description>虛擬世界法規調適計畫預計將於105年4月開始，在行政院進行連續4場的線上諮詢會議，並同步於LivehouseIn進行線上直播! （會議時間請持續關注本平台最新資訊）


4月討論主題為「數位匯流五法」：4/6「電子通訊傳播」、4/7「電信基礎設施與資源」及「電信事業」、4/11「有線多頻道平台服務」，還有4/12「無線廣播電視與頻道」。身處於多螢時代，數位生活大大改變了消費使用行為，包括數據流量成長、彈性兼具效率的網路架構、網路資通訊安全、無線電頻率資源等，匯流衍生出創新的服務模式，商業模式也隨之更貼近消費需求。如何在資源有效運用及網路安全之基礎上，朝向匯流的競爭趨力？本次會議將以匯流五法為討論重點，規劃相關主題，並邀請相關部會、學者專家、社群參與者以及行政院青年顧問團參與。本議題目前正透過問卷系統蒐集社會大眾對於本議題之相關看法，歡迎各界上網瀏覽並分享您的意見。
</description><pubDate>Wed, 23 Mar 2016 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 10：網路賣酒預計將於3月31日登場</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=58</link><description>

虛擬世界法規調適計畫預計將於105年3月31日晚上七時，在行政院進行第十場的線上諮詢會議，並同步於LivehouseIn進行線上直播! （會議時間請持續關注本平台最新資訊）


本次討論主題為「網路賣酒」。近年來網路及電子購物日益發達，交易方式不斷推陳出新，態樣多元，有網路購物業者及酒類相關業者不斷建議比照國外開放網路販酒。為避免兒少輕易取得酒品，實體及網路應如何管制，如何落實？本次會議將以試辦性質開放網路賣酒為討論重點，並邀請相關部會、學者專家、社群參與者以及行政院青年顧問團參與。本議題目前正透過問卷系統蒐集社會大眾對於本議題之相觀看法，歡迎各界上網瀏覽並分享您的意見。
</description><pubDate>Tue, 08 Mar 2016 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 9：個人資料去識別化預計將於2月23日登場</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=57</link><description>


;

虛擬世界法規調適計畫預計將於105年2月23日晚上七時，在行政院進行第九場的線上諮詢會議，並同步於LivehouseIn進行線上直播!;（會議時間請持續關注本平台最新資訊）

本次討論主題為「個人資料去識別化」。臺灣2015年有關開放資料(open data)從全球第11名躍升為第1名，於此同時，與資訊隱私息息相關的「個人資料保護法」部分條文於2015年12月30日修正通過。資料開放的風潮下，隱私如何迎風而立？本次會議將以個人資料去識別化之作法與風險為討論重點，並邀請相關部會、學者專家、社群參與者以及行政院青年顧問團參與。本議題目前正透過問卷系統蒐集社會大眾對於本議題之相關看法，歡迎各界上網瀏覽並分享您的意見，歡迎踴躍參與！！

</description><pubDate>Fri, 05 Feb 2016 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 8 : 共享經濟(住宿分享) 將於10月1日登場</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=56</link><description>

;

虛擬世界法規調適計畫將於104年10月1日(星期四) 晚上七時，進行第八場的諮詢會議，並同步進行線上直播!

;

本次討論主題為「共享經濟」。共享經濟近年來在全世界各地蓬勃發展，然而此一新興商務模式卻對傳統產業法制產生衝擊，例如Uber之於交通運輸法規，Airbnb之於旅遊業法規。本次會議將以Airbnb等類住宿分享經濟為討論重點，並邀請交通部以及Airbnb参與。本議題目前正透過問卷系統蒐集社會大眾對於本議題之相關看法，歡迎各界上網瀏覽並分享您的意見。

;

;
</description><pubDate>Thu, 24 Sep 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 6的相關紀錄已開放供查閱!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=54</link><description>

;

;

;

想回顧104年8月13日虛擬世界發展法規調適線上諮詢會議Part 6之精彩歷程嗎?

影片重播檔、會議紀錄以及直播聊天室的紀錄檔現已公開於活動頁面，歡迎各界流覽!

路徑：「首頁」&amp;rarr;「交流與互動」&amp;rarr;「虛擬世界法規調適諮詢會議專區」&amp;rarr;「虛擬世界發展法規調適線上諮詢會議Part 6」

為使未來能即時修正會議紀錄，以提昇會議記錄呈現品質，從本場次線上諮詢會議起，會議紀錄將改放置hackpad平台上。

操作說明如下：

1、首先，請先註冊平台會員，申請帳號密碼，或直接以Google、Facebook帳號登入。

2、未來若需要修改會議紀錄內容，僅需登入平台帳號密碼，即可立即修正。

;

;
</description><pubDate>Wed, 26 Aug 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 7 : 共享經濟  將於8月27日登場</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=55</link><description>

;

虛擬世界法規調適計畫將於104年8月27日(星期四) 晚上七時，進行第七場的諮詢會議，並同步進行線上直播!

;

本次討論主題為「共享經濟」。共享經濟近年來在全世界各地蓬勃發展，然而此一新興商務模式卻對傳統產業法制產生衝擊，例如Uber之於交通運輸法規，Airbnb之於旅遊業法規。本次會議將以Uber與交通運輸法規為討論重點，邀請交通部以及Uber列席報告。在之前，本議題已透過polis問卷系統蒐集社會大眾對於本議題之相關看法，歡迎各界上網瀏覽並提供數據分析報告。

;

歡迎各位關心虛擬世界發展的朋友，透過網路一同参與。

;
</description><pubDate>Fri, 21 Aug 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】UberX意見徵集已圓滿達成目標，歡迎各界提供數據分析報告!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=53</link><description>Uber等交通客運app近年在世界各地引起交通運輸管理與法制爭議。

有些國家對此已經提出特別法制規範，例如美國加州與科羅拉多州、菲律賓、墨西哥市等等。

然而有些國家則是採取禁止的態度，例如法國與德國等等。

為了解各方對於以Uber為例的交通運輸共享經濟之看法，透過polis平台進行UberX 自用車載客意見徵集。

徵集意見到 8/15 中午時，「自用車載客」徵集告一段落，共有926 位朋友參與，收到 80 則意見、30000 人次互動。

原始資料公開如附，歡迎對資料科學、數據分析有興趣的朋友們下載利用，並透過vtaiwan臉書告訴我們這些資料代表的意義，或逕寄送給本消息聯絡人。

現已有Uber主動提供polis數據分析報告如附，如有其它分析報告將一併更新至本則消息。

聯絡人：資策會科法所 謝研究員 stellamshsieh@iii.org.tw;; 李研究員 chihyingli@iii.org.tw
</description><pubDate>Fri, 21 Aug 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】「網路霸凌」討論區上線</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=52</link><description>
虛擬世界法規調適最新一波討論議題:網路霸凌(cyberbullying)上線囉!!!!

隨著智慧手機及電腦網路深入日常生活，網路霸凌所涉及之公然侮辱、誹謗、恐嚇、加工自殺、妨害秘密等問題，可能違反我國民法、刑法、社會秩序維護法等相關法律。為當前引起社會各界廣大同情及關注之重要議題。

邀請大家一起参與，提供您寶貴的意見，凝聚共識，營造美好和善的網路環境!
並請您持續關心vTaiwan討論區。

</description><pubDate>Thu, 25 Jun 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】線上諮詢會議Part 5的相關紀錄已開放供查閱!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=51</link><description>想回顧104年5月14日虛擬世界發展法規調適線上諮詢會議Part 5之精彩歷程嗎?

影片重播檔、會議紀錄以及直播聊天室的紀錄檔現已公開於活動頁面，歡迎各界流覽!

路徑：「首頁」&amp;rarr;「交流與互動」&amp;rarr;「虛擬世界法規調適諮詢會議專區」&amp;rarr;「虛擬世界發展法規調適線上諮詢會議Part 5」
</description><pubDate>Mon, 25 May 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】線上諮詢會議Part 4的相關紀錄已開放供查閱!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=50</link><description>想回顧104年4月24日虛擬世界發展法規調適線上諮詢會議Part 4之精彩歷程嗎?

影片重播檔、會議紀錄以及直播聊天室的紀錄檔現已公開於活動頁面，歡迎各界流覽!

路徑：「首頁」&amp;rarr;「交流與互動」&amp;rarr;「虛擬世界法規調適諮詢會議專區」&amp;rarr;「虛擬世界發展法規調適線上諮詢會議Part 4」
</description><pubDate>Fri, 08 May 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 5 電傳勞動&amp;網路交易，將於5月14日舉辦</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=49</link><description>
虛擬世界發展法規調適線上諮詢會議Part 5即將於5月14日(星期四)晚上七時登場，本次將討論電傳勞動以及網路交易，主要具體內容為電傳勞動法制之建構與調適以及「零售業等網路交易定型化契約應記載及不得記載事項」之修正。

本次會議主持人為PanSci 泛科學暨娛樂重擊之總編輯鄭國威先生。活動議程以及相關會議資料請至活動頁面查詢下載。

本次活動將同步透過Livehouse.in平台進行直播，歡迎各界透過網路共襄盛舉。
</description><pubDate>Tue, 05 May 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】線上諮詢會議Part 3的相關紀錄已開放供查閱!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=47</link><description>想回顧104年4月14日虛擬世界發展法規調適線上諮詢會議Part 3之精彩歷程嗎?
影片重播檔、會議紀錄以及直播聊天室的紀錄檔現已公開於活動頁面，歡迎各界流覽!
路徑：「首頁」&amp;rarr;「交流與互動」&amp;rarr;「虛擬世界法規調適諮詢會議專區」&amp;rarr;「虛擬世界發展法規調適線上諮詢會議Part 3」
</description><pubDate>Fri, 01 May 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 4 (遠距醫療照護、個人資料利用與去識別化)將於4月24日登場</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=46</link><description>
;

虛擬世界發展法規調適線上諮詢會議Part 4即將在104年4月24日晚上七時登場。本次會議討論主題包含「遠距醫療照護」以及「個人資料利用與去識別化」。將分別由衛福部以及法務部進行報告。其中「遠距醫療照護」之具體內容包含「遠距照護」、「遠距診療」以及「藥物網路販賣」。詳請見vTaiwan討論區。

本次活動將由學悅科技創辦人趙式隆先生擔任主持人，並同步於虛擬世界法規調適交流平台以及LIVEhouse.in進行直播。詳細議程以及會議資訊請見活動專頁。
</description><pubDate>Fri, 17 Apr 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】線上諮詢會議Part 2的相關紀錄已開放供查閱!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=45</link><description>想回顧104年3月24日虛擬世界發展法規調適線上諮詢會議Part 2之精彩歷程嗎?

影片重播檔、會議紀錄以及直播聊天室的紀錄檔現已公開於活動頁面，歡迎各界流覽!

路徑：「首頁」&amp;rarr;「交流與互動」&amp;rarr;「虛擬世界法規調適諮詢會議專區」&amp;rarr;「虛擬世界發展法規調適線上諮詢會議Part 2」
</description><pubDate>Wed, 01 Apr 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】線上諮詢會議Part 3 (遠距教育、開放資料例外收費原則)將於4月14日登場。</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=44</link><description>
;

暨Part 1 &amp;amp; Part 2之後，虛擬世界發展法規調適線上諮詢會議Part 3即將在104年4月14日晚上七時登場。本次會議討論主題包含「遠距教育」以及「開放資料例外收費原則」。將分別由教育部以及國發會進行報告。「遠距教育」相關討論議題包含如線上學習與學分取得、大學遠距教育實施辦法關於遠距修課相關規定的修正。另在政府資料開放方面，目前政策以「不收費為原則、收費為例外」，關於例外收費項目以及詳細作法正在廣徵各方意見。詳請見vTaiwan討論區。

本次活動將由iKala CEO程世嘉先生擔任主持人，並同步於虛擬世界法規調適交流平台以及LIVEhouse.in進行直播。詳細議程以及會議詳細資訊請見活動專頁。
</description><pubDate>Tue, 31 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】線上諮詢會議Part 1的相關紀錄已開放供查閱!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=43</link><description>想回顧104年3月12日虛擬世界發展法規調適線上諮詢會議Part;1之精彩歷程嗎?

影片重播檔、會議紀錄以及直播聊天室的紀錄檔現已公開於活動頁面，歡迎各界流覽!

路徑：「首頁」&amp;rarr;「交流與互動」&amp;rarr;「虛擬世界法規調適諮詢會議專區」&amp;rarr;「虛擬世界發展法規調適線上諮詢會議Part 1」
</description><pubDate>Fri, 20 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】股權式群眾募資法制規劃草案出爐</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=42</link><description>為推動股群式群眾募資發展，金管會已於104年3月13日發文預告修正「證券商設置標

準」部分條文、「證券商管理規則」第九條、第四十五條之一及「證券商負責人與業務

人員管理規則」第二十一條之一草案。(金管證券字第1040007515號)

配合金管會之政策規劃，財團法人中華民國證券櫃檯買賣中心也已同步完成「證券商經

營股權性質群眾募資管理辦法草案」。
</description><pubDate>Wed, 18 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】虛擬世界法規調適諮詢會議Part 2股權式群眾募資將在3月24日晚間七時登場</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=41</link><description>


金管會擬開放證券商以網路平台經營股權式群眾募資，您對於金管會的新政策有任何看法嗎?

虛擬世界法規調適計畫將於104年3月24日舉辦第二場諮詢會議，由金管會就其股權式群眾募資方案進行報告，並邀請相關學者專家與會進行討論。

本次會議將於晚上七時在行政院舉辦，並同步進行現場直播!

歡迎各界關心此議題的朋友，上線與我們一起討論。

議題討論歷程及相關資訊請見 虛擬世界法規調適交流平台&amp;rarr;交流與互動&amp;rarr;vTaiwan討論區。

3月24日會議相關資訊請見 虛擬世界法規調適交流平台&amp;rarr;交流與互動&amp;rarr;虛擬世界法規調適諮詢會議專區。
</description><pubDate>Wed, 18 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】 國家發展委員會誠摯的邀請您共同協作「網路智慧新臺灣政策白皮書」</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=40</link><description>為制訂我國未來網路應用發展方向，行政院刻正規劃研訂「網路智慧新臺灣政策白皮書」，作為未來政府推動資訊服務的藍圖。 白皮書由五大構面組成，包括「基礎環境」、「透明治理」、「智慧生活」、「網路經濟」、「智慧國土」，目前各部會透過網路討論以及實體會議溝通，已徵集各方意見，並且即將完成白皮書初稿。 國家發展委員會誠摯的邀請您上公共政策網路參與平台（http://join.gov.tw）共同參與討論，以使行動計畫內容符合民眾未來的期望。謝謝您！;
</description><pubDate>Mon, 16 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】主要國家電傳勞動規範</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=39</link><description>電傳勞動時代來臨,整個世界都是您的辦公室,您是否有利用電腦及網路到處工作的經驗?
彈性的工作地點,時間,方式已為先進國家發展趨勢,

歡迎上vTaiwan討論區，分享您的看法 : https://talk.vtaiwan.tw/t/topic/188
關於日本、香港、韓國、新加坡的規定，請參考附檔。
</description><pubDate>Wed, 11 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】虛擬世界發展法規調適線上諮詢會議部會專題報告簡報</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=37</link><description>虛擬世界發展法規調適線上諮詢會議即將於3月12日19：00-21：10隆重登場。本次討論主軸為「閉鎖型公司」和「網路交易課稅」。為促進會議討論順利進行，主管部會事先提供專題報告簡報，歡迎各界瀏覽。

誠摯邀請您持續至vTaiwan線上法規討論平台https://vtaiwan.tw/ 參與討論，發表對「閉鎖型公司」和「網路交易課稅」法規調適和政策修訂之寶貴意見。3月12日會議開始前之留言，皆有可能在會議中被提出討論。
</description><pubDate>Tue, 10 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【活動公告】3/12 虛擬世界發展法規調適線上諮詢會議</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=36</link><description>除了vTaiwan討論區的筆墨交流，3月12日各部會、學者專家以及討論區的工作成員進行面對面的意見溝通。本次會議將於行政院舉辦，主題為「打造臺灣成為網路公司的樞紐－閉鎖型股份有限公司及網路交易課稅」，並同步透過LIVEhouse.in進行線上直播! 本平台也將轉接LIVEhouse.in進行直播! 敬請大家3/12晚間七點準時觀賞。

相關訊息請見「交流與互動」&amp;rarr;「虛擬世界法規調適諮詢會議」(http://www.vtaiwan.org.tw/model.aspx?no=232 )
</description><pubDate>Fri, 06 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】vTaiwan FB，請大家來按讚!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=35</link><description>虛擬世界法規調適計畫有FB粉絲團囉! 想掌握vTaiwan的大小事嗎?

請大家到FB粉絲團給個讚! https://www.facebook.com/vtaiwan.tw
</description><pubDate>Fri, 06 Mar 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】公司法修正草案「閉鎖性股份有限公司」-行政部門委託學者研究之草案</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=34</link><description>科技新創事業是引領台灣未來的關鍵所在。而科技新創事業能否蓬勃發展，其法制面上的關鍵則在於創業家與投資人間能否有更精緻、周延的契約安排、組織規劃來因應科技新創事業本質上的高風險，以追求未來可能實現的高報酬。然而，在現行公司法中，不論是有限公司或是股份有限公司的規範，都存在著許多管制性的強行規定，大幅限縮了創業家與投資人的規劃空間。

實則，創業家與投資人間之權利義務的規劃空間，不僅有利於科技新創事業的發展，傳統的中小企業亦有其需求。蓋不論是科技新創事業或是中小企業，都非常需要股東間的同心協力，緊密合作，因此其發展初期，股東結構常呈現相當的閉鎖性，從此一特性觀之，與學理上常稱的「閉鎖性公司」不謀而合。對於此類公司而言，相較於立法者為大型公司量身定作的股份有限公司的規定，公司章程或股東協議顯然是安排公司與股東間權利義務的更好的機制。爰此，此一草案大幅度地放寬現有公司法的管制性規定，以創設符合科技新創事業與中小企業發展的法律環境，期待未來創業家與投資人自行創造出最有利於該公司運作的公司章程或契約規範。

歡迎各界對於草案內容提供寶貴意見，請上vTaiwan討論區: https://vtaiwan.tw/#!/
</description><pubDate>Fri, 06 Feb 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】虛擬世界法規調適討論區邀請您参與討論!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=33</link><description>為了進行虛擬世界法規調適，我們開設了「vTaiwan討論區(https://vtaiwan.tw/#!/)」蒐集各方意見，以觀測法規調適需求、決定法規調適方向。

討論區的意見徵集乃是由相關主管機關主導，將彙整做為主管機關政策擬定之參考。

配合計劃時程，目前開設「群眾募資」以及「閉鎖性公司」專題討論區。


邀請您共同参與討論!

;
</description><pubDate>Fri, 30 Jan 2015 00:00:00 GMT</pubDate></item><item><title>【網站公告】虛擬世界法規交流平台開站，各單元內容陸續建置中，敬請期待!</title><link>https://www.vtaiwan.org.tw/news_detail.aspx?no=82&amp;d=30</link><description>虛擬世界法規交流平台開站，各單元內容陸續建置中，敬請期待!
</description><pubDate>Fri, 30 Jan 2015 00:00:00 GMT</pubDate></item></channel></rss>